# Generated by Django 3.1.4 on 2021-04-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('work_type', models.CharField(choices=[('Contract', 'Contract'), ('Full Time', 'Full Time'), ('Freelance', 'Freelance')], default='Contract', max_length=20)),
                ('month_started', models.IntegerField()),
                ('year_started', models.IntegerField()),
                ('month_ended', models.IntegerField()),
                ('year_ended', models.IntegerField()),
                ('work_location', models.CharField(max_length=200)),
                ('job_role', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.industryexperience')),
            ],
        ),
        migrations.CreateModel(
            name='JobAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('project_id', models.CharField(max_length=200)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.jobdescription')),
            ],
        ),
    ]
