# Generated by Django 3.1.4 on 2021-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobaccomplishment',
            name='short_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
