# Generated by Django 3.1.4 on 2021-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_jobaccomplishment_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaccomplishment',
            name='short_title',
            field=models.CharField(default='MISSING SHORT TITLE', max_length=200),
        ),
    ]
