# Generated by Django 3.1.4 on 2021-04-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210408_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaccomplishment',
            name='project_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
