# Generated by Django 3.1.4 on 2021-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210408_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='company_link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
