# Generated by Django 3.1.4 on 2021-04-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210413_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.cardheaders'),
        ),
    ]
