# Generated by Django 3.1.4 on 2021-04-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210413_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company / Institution / Organisation')),
                ('company_link', models.URLField(max_length=500, null=True, verbose_name='Website')),
                ('work_type', models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Full Time', 'Full Time'), ('Freelance', 'Freelance')], default='Contract', max_length=20)),
                ('month_started', models.IntegerField()),
                ('year_started', models.IntegerField()),
                ('month_ended', models.IntegerField()),
                ('year_ended', models.IntegerField()),
                ('work_location', models.CharField(max_length=200, verbose_name='Location')),
                ('job_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.cardheaders', verbose_name='Role / Certification')),
            ],
        ),
    ]
