# Generated by Django 3.1.4 on 2021-04-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(default='MISSING SHORT TITLE', max_length=200)),
                ('description', models.TextField()),
                ('project_id', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.jobdescription', verbose_name='Company / Institution / Organisation')),
            ],
        ),
    ]
