# Generated by Django 3.1.4 on 2021-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_accomplishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='company',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
