# Generated by Django 3.1.4 on 2021-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210413_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishment',
            name='company',
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='company_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
