# Generated by Django 3.1.4 on 2021-04-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210413_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishment',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='description',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.cardheaders', verbose_name='Role / Certification'),
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_key', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.description')),
            ],
        ),
    ]
