# Generated by Django 3.1.4 on 2021-04-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210413_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.description', verbose_name='Company / Institution / Organisation'),
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
