# Generated by Django 3.1.4 on 2021-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210415_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsectionheader',
            name='section_image',
            field=models.ImageField(blank=True, null=True, upload_to='cv_icons'),
        ),
    ]
