# Generated by Django 3.1.4 on 2021-04-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_accomplishment_include_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='month_ended',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='work_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='description',
            name='year_ended',
            field=models.IntegerField(blank=True),
        ),
    ]
