# Generated by Django 3.1.4 on 2021-04-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20210415_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['-year_ended', '-month_ended']},
        ),
    ]
