# Generated by Django 3.1.4 on 2021-04-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20210416_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='month_started',
            field=models.IntegerField(default=0, verbose_name='Month Started (enter 0 if not available)'),
        ),
        migrations.AlterField(
            model_name='description',
            name='year_started',
            field=models.IntegerField(default=0, verbose_name='Year Started (enter 0 if not available)'),
        ),
    ]
