# Generated by Django 3.1.4 on 2021-04-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20210416_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['-year_ended', '-month_ended', '-year_started', '-month_started']},
        ),
    ]
